services:
  web:
    image: client_management_system
    container_name: cms_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8081:8081"
      - "8444:8444"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./static:/static
      - ./media:/media
    restart: always
    depends_on:
      - web