# Generated by Django 5.0.7 on 2024-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('salutation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_head_of_family', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
