# Generated by Django 5.0.7 on 2024-07-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_head_of_family',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
    ]
