# Generated by Django 5.0.7 on 2024-07-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_is_head_of_family_remove_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_name',
        ),
    ]
