# Generated by Django 5.0.7 on 2024-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='city',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='comments',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_type',
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
