# Generated by Django 4.2.16 on 2024-11-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_city_trip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
