name: Django CI/CD

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test  # Или любой другой тестовый фреймворк, который вы используете

      - name: Build and collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" -avz --exclude='.git' --exclude='venv' ./ $USERNAME@$SERVER:/var/www/pavlyuk.online/
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
            cd /var/www/client-management-system
            source /var/www/client-management-system/venv/bin/activate  # Обновите путь к вашему виртуальному окружению
            python manage.py migrate
            sudo systemctl restart apache2  # Перезапуск Apache
          EOF
